version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: ecommerce
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d ecommerce"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://demo:demo@db:5432/ecommerce
      INSTANCE_NAME: api
      RUN_DB_INIT: "true"
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  gateway:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://demo:demo@db:5432/ecommerce
      INSTANCE_NAME: gateway
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8001"
    command: ["uvicorn", "app.security.gateway:app", "--host", "0.0.0.0", "--port", "8001"]

volumes:
  db_data:
